alert ("Hay...............:)")
alert ("Kamu ko manis banget si")
alert ("Udah manis,cantik,baik lagi")
alert ("Boleh ga aku bilang sesuatu?")
alert ("Aku kangen kamu ehhh")
alert ("Aku rindu")
alert ("Jangan senyum-senyum sendiri napa wkwk")
alert ("Udah ah akunya maluu hihi")
alert ("Babayyyyy muahhhh wkwk")